sudo: false
language: php
cache:
  directories:
    - $HOME/.composer/cache
    - vendor
matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
before_script:
  - composer self-update
  - composer install
script:
 - phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  email: false

